version: '3.3'
services:
  snake:
    image: 'haffose/node-chat-app'  # Replace 'latest' with the specific tag if needed
    environment:
      - PORT=3000
    ports:
      - "80:3000"
    volumes:
      - ./:/app
